sudo: false
language: php
php:
  - 7.0

env:
  - TRAVIS_NODE_VERSION="7.5" CXX="g++-4.8"

matrix:
  fast_finish: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

branches:
  only:
  - master

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - node_modules
    - vendor

before_install:
  - composer self-update

install:
  - source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION && nvm use $TRAVIS_NODE_VERSION 
  - travis_retry npm install -g npm@latest
  - travis_retry npm install -g eslint
  - travis_retry npm install -g codecov
  - node -v && npm -v
  - npm rebuild
  - travis_retry npm install
  - npm prune
  - composer install -o --prefer-dist --no-interaction

script:
  - npm run test
  - npm run "build:production"
  # - composer test

after_success:
  - set -e
  - sudo apt-get install -y lftp
  - lftp -c "
      set ftps:initial-prot '';
      set ftp:ssl-force true;
      set ftp:ssl-protect-data true;
      set ssl:verify-certificate false;
      open ftp://$FTP_USER:$FTP_PASS@$FTP_HOST:21;
      mirror -eRv -P 10 -x ^\. -x node_modules/ -x resources/assets/ $FTP_DIR .;
      quit;"
  - codecov
